os:
  - linux
  - osx
  - windows
language: rust
cache: cargo

# Run the script on stable, beta and nightly channels
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add clippy

script:
  # fail when encountering warnings
  - cargo clippy -- -D warnings
  # run tests
  - cargo test
